FROM php:7.3-cli

RUN apt-get update -y && apt-get install -y \
        libmcrypt-dev \
        git

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install \
        pdo mbstring \
        mysqli \
        pdo pdo_mysql

WORKDIR /var/www/html
COPY . /var/www/html

RUN composer install

EXPOSE 8080
CMD php bin/console server:run 0.0.0.0:8080
