version: '3.4'
services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    privileged: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html
    networks:
      - default

  mysql:
    build:
      context: ./
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - default

  phpmyadmin:
    links:
      - mysql
    image: phpmyadmin/phpmyadmin
    ports:
      - "7777:8080"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - PMA_HOST=mysql
    networks:
      - default